<h1><center>Natural Language Processing</center></h1>

<h3><center>NLP 14</center></h3>

![hM0xGrmJw](https://miro.medium.com/max/720/1*PGB0w1JZslqA-hM0xGrmJw.gif)

# Topics
1.	Introduction to Natural Language Processing
2.	Why learn NLP?
3.	Let's start playing with Python!
4.	Text Wrangling and Cleansing
 - Sentence splitter
 - Tokenization
 - Stemming         
 - Lemmatization    
 - Stop word removal
 - Diving into NLTK
5.	Vectorizing with Python
 - Count Vectorizer 
 - TF-IDF Vectorizer
6.	Modelling with Python 
 - Classification 
 - Clustering
 - Sentiment Analysis 

Kinda Done <---------------------------------------------------- **This is where we are**

# Basic flow
![](https://devopedia.org/images/article/230/4727.1572189926.png)

# Word2Vec

In [131]:
import gensim
from gensim.models import Word2Vec

In [132]:
path = '~/siddharthkothotya/github_content/non_github/model/GoogleNews-vectors-negative300.bin.gz'

In [133]:
model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=True) 

In [134]:
model

In [141]:
model['my']

array([ 1.44531250e-01,  4.71191406e-02,  1.00585938e-01,  3.28125000e-01,
       -2.02636719e-02, -1.72119141e-02,  3.78417969e-02, -1.34765625e-01,
       -1.25976562e-01,  9.71679688e-02, -9.17968750e-02, -1.02539062e-01,
        1.99890137e-03, -3.58886719e-02, -4.02343750e-01,  5.29785156e-02,
        3.12500000e-01,  1.15234375e-01,  1.49414062e-01, -1.45507812e-01,
       -2.09960938e-02,  1.90429688e-01,  1.31835938e-01,  4.51660156e-02,
       -1.43554688e-01,  5.29785156e-02, -1.01562500e-01,  1.70898438e-02,
        1.11328125e-01, -8.39843750e-02,  2.40234375e-01,  2.67333984e-02,
        2.25830078e-02,  2.19726562e-01,  7.59124756e-04, -1.08886719e-01,
        1.39648438e-01,  7.71484375e-02,  1.11083984e-02, -2.68554688e-02,
       -3.15856934e-03,  1.24511719e-02,  3.02734375e-01,  1.13525391e-02,
        2.85156250e-01,  1.98242188e-01, -1.22680664e-02,  2.28271484e-02,
        1.80664062e-01, -8.48388672e-03,  9.32617188e-02,  5.02929688e-02,
        5.44433594e-02,  

In [142]:
len(model['king'])

300

In [144]:
model['queen']

array([ 0.00524902, -0.14355469, -0.06933594,  0.12353516,  0.13183594,
       -0.08886719, -0.07128906, -0.21679688, -0.19726562,  0.05566406,
       -0.07568359, -0.38085938,  0.10400391, -0.00081635,  0.1328125 ,
        0.11279297,  0.07275391, -0.046875  ,  0.06591797,  0.09423828,
        0.19042969,  0.13671875, -0.23632812, -0.11865234,  0.06542969,
       -0.05322266, -0.30859375,  0.09179688,  0.18847656, -0.16699219,
       -0.15625   , -0.13085938, -0.08251953,  0.21289062, -0.35546875,
       -0.13183594,  0.09619141,  0.26367188, -0.09472656,  0.18359375,
        0.10693359, -0.41601562,  0.26953125, -0.02770996,  0.17578125,
       -0.11279297, -0.00411987,  0.14550781,  0.15625   ,  0.26757812,
       -0.01794434,  0.09863281,  0.05297852, -0.03125   , -0.16308594,
       -0.05810547, -0.34375   , -0.17285156,  0.11425781, -0.09033203,
        0.13476562,  0.27929688, -0.04980469,  0.12988281,  0.17578125,
       -0.22167969, -0.01190186,  0.140625  , -0.18164062,  0.11

# Try and Except

In [145]:
dict_a = {'car':'i20','brand':'Hyundai'}

In [148]:
dict_a['car']

'i20'

In [150]:
dict_a['ca']

KeyError: 'ca'

In [151]:
dict_a.get('car')

'i20'

In [152]:
dict_a.get('ca')

### Similarly

In [154]:
model['car']

array([ 0.13085938,  0.00842285,  0.03344727, -0.05883789,  0.04003906,
       -0.14257812,  0.04931641, -0.16894531,  0.20898438,  0.11962891,
        0.18066406, -0.25      , -0.10400391, -0.10742188, -0.01879883,
        0.05200195, -0.00216675,  0.06445312,  0.14453125, -0.04541016,
        0.16113281, -0.01611328, -0.03088379,  0.08447266,  0.16210938,
        0.04467773, -0.15527344,  0.25390625,  0.33984375,  0.00756836,
       -0.25585938, -0.01733398, -0.03295898,  0.16308594, -0.12597656,
       -0.09912109,  0.16503906,  0.06884766, -0.18945312,  0.02832031,
       -0.0534668 , -0.03063965,  0.11083984,  0.24121094, -0.234375  ,
        0.12353516, -0.00294495,  0.1484375 ,  0.33203125,  0.05249023,
       -0.20019531,  0.37695312,  0.12255859,  0.11425781, -0.17675781,
        0.10009766,  0.0030365 ,  0.26757812,  0.20117188,  0.03710938,
        0.11083984, -0.09814453, -0.3125    ,  0.03515625,  0.02832031,
        0.26171875, -0.08642578, -0.02258301, -0.05834961, -0.00

In [157]:
model['asjkdfhlkasjdhf']

KeyError: "Key 'asjkdfhlkasjdhf' not present"

In [159]:
model.get('car')

AttributeError: 'KeyedVectors' object has no attribute 'get'

In [160]:
type(model)

gensim.models.keyedvectors.KeyedVectors

# Now, let's try this in practice

In [164]:
list_a = ['This', 'sentence', 'kajsdlfkjahsd', 'my', 'sentence']

In [165]:
temp = []
for i in list_a:
    temp.append(model[i])

KeyError: "Key 'kajsdlfkjahsd' not present"

In [163]:
temp

[array([-0.2890625 ,  0.19921875,  0.16015625,  0.02526855, -0.23632812,
         0.10205078,  0.06640625, -0.16503906,  0.12597656,  0.22070312,
         0.05517578, -0.28710938, -0.02148438,  0.05541992,  0.01574707,
         0.29296875,  0.19433594, -0.01531982,  0.03955078, -0.21484375,
         0.00994873,  0.16015625,  0.07958984, -0.05932617,  0.12353516,
        -0.27148438, -0.10205078,  0.078125  , -0.07519531,  0.22363281,
         0.16210938, -0.04614258,  0.12304688,  0.07275391,  0.25      ,
         0.0072937 , -0.38867188,  0.10644531,  0.20996094,  0.06103516,
         0.10107422,  0.16894531, -0.15429688, -0.08251953,  0.06542969,
        -0.12255859, -0.11621094,  0.04248047,  0.08251953,  0.09716797,
        -0.05371094,  0.125     ,  0.15039062, -0.09228516,  0.23925781,
         0.15234375,  0.1796875 , -0.26171875,  0.15429688,  0.09619141,
        -0.30859375, -0.05224609, -0.18652344, -0.24414062, -0.0612793 ,
        -0.12695312,  0.14160156, -0.03295898,  0.0

# To solve this, we use try and except

In [169]:
# Standard temaplate
try:
    print('Trying')
except:
    print('Except happened')

Trying


# Using try and Except to solve our problem

In [173]:
temp = []
for i in list_a:
    try:
        temp.append(model[i])
    except:
        pass


In [174]:
list_a

['This', 'sentence', 'kajsdlfkjahsd', 'my', 'sentence']

In [176]:
len(temp)

4

In [177]:
temp

[array([-0.2890625 ,  0.19921875,  0.16015625,  0.02526855, -0.23632812,
         0.10205078,  0.06640625, -0.16503906,  0.12597656,  0.22070312,
         0.05517578, -0.28710938, -0.02148438,  0.05541992,  0.01574707,
         0.29296875,  0.19433594, -0.01531982,  0.03955078, -0.21484375,
         0.00994873,  0.16015625,  0.07958984, -0.05932617,  0.12353516,
        -0.27148438, -0.10205078,  0.078125  , -0.07519531,  0.22363281,
         0.16210938, -0.04614258,  0.12304688,  0.07275391,  0.25      ,
         0.0072937 , -0.38867188,  0.10644531,  0.20996094,  0.06103516,
         0.10107422,  0.16894531, -0.15429688, -0.08251953,  0.06542969,
        -0.12255859, -0.11621094,  0.04248047,  0.08251953,  0.09716797,
        -0.05371094,  0.125     ,  0.15039062, -0.09228516,  0.23925781,
         0.15234375,  0.1796875 , -0.26171875,  0.15429688,  0.09619141,
        -0.30859375, -0.05224609, -0.18652344, -0.24414062, -0.0612793 ,
        -0.12695312,  0.14160156, -0.03295898,  0.0

In [179]:
len(temp[0])

300

In [185]:
sum(temp)/len(temp)

array([ 2.27050781e-02, -5.56030273e-02,  3.03466797e-01,  1.16882324e-02,
        1.87805176e-01,  7.51647949e-02,  1.65710449e-01, -2.53906250e-02,
        1.57470703e-02,  1.70776367e-01,  9.48486328e-02, -1.46972656e-01,
       -1.00086212e-01,  8.44726562e-02, -9.82894897e-02,  1.97326660e-01,
        2.81982422e-01,  9.62677002e-02,  6.95800781e-03, -3.15673828e-01,
        2.33459473e-03,  1.18896484e-01,  8.54492188e-04,  7.32421875e-03,
        1.70776367e-01, -3.53454590e-01, -2.07519531e-02,  2.54898071e-02,
        2.43530273e-02,  2.73193359e-01,  4.93164062e-02, -1.07391357e-01,
       -9.05456543e-02,  1.88354492e-01,  1.31049156e-01,  1.48429871e-01,
       -9.27734375e-03,  3.47900391e-02, -1.10748291e-01,  2.26318359e-01,
       -4.77867126e-02,  6.90307617e-02,  3.22875977e-02, -1.23260498e-01,
        9.84497070e-02, -1.59912109e-02, -4.45098877e-02,  5.19714355e-02,
       -9.43603516e-02,  1.73538208e-01,  6.16455078e-02, -1.91650391e-02,
       -4.64477539e-02,  

In [46]:
temp = []
for i in list_a:
    try:
        temp.append(model[i])
    except:
        pass
result = sum(temp)/len(temp)

In [203]:
a = model['success']

In [204]:
b = model['victory']

In [195]:
import numpy as np
from numpy.linalg import norm
 
# compute cosine similarity
def calculate_cosine(a,b):
    cosine = np.dot(a,b)/(norm(a)*norm(b))
    print("Cosine Similarity:", cosine)
    return cosine

In [205]:
calculate_cosine(a,b)

Cosine Similarity: 0.35148013


0.35148013

# Making it a function

In [210]:
from nltk.tokenize import word_tokenize
def word2vec(x):
    # Making everything lowercase
    x = str(x)
    x = x.lower()

    # Tokenizing it
    tokenized_list = word_tokenize(x)
    
    temp = []
    for i in tokenized_list:
        try:
            temp.append(model[i])
        except:
            pass
    
    if len(temp) == 0:
        result = 0
    else:    
        result = sum(temp)/len(temp)
    
    return result

In [211]:
# Let's try the funciton
word2vec('')

0

# Reading data

In [212]:
import pandas as pd
df = pd.read_csv('datasets/ecommerceDataset.csv',header=None, names=['Category','Text'])

In [213]:
df

Category                                               Text
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50425 rows x 2 columns]

In [215]:
df = df.sample(n=500)

In [217]:
df

Category  \
31679  Clothing & Accessories   
30302                   Books   
33777  Clothing & Accessories   
23715                   Books   
1665                Household   
...                       ...   
390                 Household   
23016                   Books   
13395               Household   
25372                   Books   
11780               Household   

                                                    Text  
31679  Harissons Sleep Sac 225cm Sleeping Mat for Tre...  
30302  Quarantine: Stories Review “There are great re...  
33777  Q-rious Women's Cotton Lycra Trousers/Pants/Ch...  
23715  Linguistics: A Complete Introduction: Teach Yo...  
1665   Spacewood Texas 2 Door Wardrobe (Woodpore Fini...  
...                                                  ...  
390    Ilu Dream Catcher Wall Hanging Handmade Beaded...  
23016  A Book of Essays Revised 26th Edition 2018 Thi...  
13395  Bajaj Majesty JX 4 450-Watt Juicer Mixer Grind...  
25372  Seabiscuit: An American Legend Review “Fascina...  
11780                          JVL Small Butter Dish Box  

[500 rows x 2 columns]

In [90]:
df = df.reset_index(drop=True)

In [220]:
df

Category  \
31679  Clothing & Accessories   
30302                   Books   
33777  Clothing & Accessories   
23715                   Books   
1665                Household   
...                       ...   
390                 Household   
23016                   Books   
13395               Household   
25372                   Books   
11780               Household   

                                                    Text  
31679  Harissons Sleep Sac 225cm Sleeping Mat for Tre...  
30302  Quarantine: Stories Review “There are great re...  
33777  Q-rious Women's Cotton Lycra Trousers/Pants/Ch...  
23715  Linguistics: A Complete Introduction: Teach Yo...  
1665   Spacewood Texas 2 Door Wardrobe (Woodpore Fini...  
...                                                  ...  
390    Ilu Dream Catcher Wall Hanging Handmade Beaded...  
23016  A Book of Essays Revised 26th Edition 2018 Thi...  
13395  Bajaj Majesty JX 4 450-Watt Juicer Mixer Grind...  
25372  Seabiscuit: An American Legend Review “Fascina...  
11780                          JVL Small Butter Dish Box  

[500 rows x 2 columns]

In [221]:
df['Text'].apply(word2vec)

31679    [0.036612954, 0.03508504, -0.10500082, 0.12875...
30302    [0.029361045, 0.051685173, 0.016846538, 0.0928...
33777    [0.016166687, 0.02288431, -0.015180588, 0.0842...
23715    [0.042582195, -0.019540293, 0.0766172, 0.08823...
1665     [-0.0022300438, 0.08558485, -0.009254597, 0.03...
                               ...                        
390      [0.025570981, 0.05713272, 0.015889348, 0.09665...
23016    [0.009421585, 0.049136046, 0.024935469, 0.0834...
13395    [0.01887354, 0.06337988, 0.020563096, 0.090091...
25372    [0.044152096, 0.036244303, 0.015659792, 0.0558...
11780    [-0.036987305, 0.076171875, -0.008911133, 0.15...
Name: Text, Length: 500, dtype: object

In [222]:
df['vectors'] = df['Text'].apply(word2vec)

In [223]:
df

Category  \
31679  Clothing & Accessories   
30302                   Books   
33777  Clothing & Accessories   
23715                   Books   
1665                Household   
...                       ...   
390                 Household   
23016                   Books   
13395               Household   
25372                   Books   
11780               Household   

                                                    Text  \
31679  Harissons Sleep Sac 225cm Sleeping Mat for Tre...   
30302  Quarantine: Stories Review “There are great re...   
33777  Q-rious Women's Cotton Lycra Trousers/Pants/Ch...   
23715  Linguistics: A Complete Introduction: Teach Yo...   
1665   Spacewood Texas 2 Door Wardrobe (Woodpore Fini...   
...                                                  ...   
390    Ilu Dream Catcher Wall Hanging Handmade Beaded...   
23016  A Book of Essays Revised 26th Edition 2018 Thi...   
13395  Bajaj Majesty JX 4 450-Watt Juicer Mixer Grind...   
25372  Seabiscuit: An American Legend Review “Fascina...   
11780                          JVL Small Butter Dish Box   

                                                 vectors  
31679  [0.036612954, 0.03508504, -0.10500082, 0.12875...  
30302  [0.029361045, 0.051685173, 0.016846538, 0.0928...  
33777  [0.016166687, 0.02288431, -0.015180588, 0.0842...  
23715  [0.042582195, -0.019540293, 0.0766172, 0.08823...  
1665   [-0.0022300438, 0.08558485, -0.009254597, 0.03...  
...                                                  ...  
390    [0.025570981, 0.05713272, 0.015889348, 0.09665...  
23016  [0.009421585, 0.049136046, 0.024935469, 0.0834...  
13395  [0.01887354, 0.06337988, 0.020563096, 0.090091...  
25372  [0.044152096, 0.036244303, 0.015659792, 0.0558...  
11780  [-0.036987305, 0.076171875, -0.008911133, 0.15...  

[500 rows x 3 columns]

In [102]:
# df['vectors'].values

# That's it 

<h1><center>Thank you</center></h1>

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzJiNTc3YjVmOTc3MTU2YzA5Y2IyY2YwYTU1NWY3NTkzNzY4Mzg0OCZjdD1n/PlTk912D95SISs2NkR/giphy.gif)